### ISSUE TITLE
.scss-lint.yml

### ISSUE THREAD

**Issue by michaelfich** [tomasbasham/ember-cli-scss-lint#11]
I noticed in the readme that this configuration file needs to specifically be `.sass-lint.yml` as opposed to `.scss-lint.yml`.  Is there any particular reason for that?

**Comment by tomasbasham** [comment]
So originally the file was `.scss-lint.yml`. This was because the addon used the Ruby implementation [scss-lint](https://github.com/brigade/scss-lint). Now however this addon uses the JavaScript implementation [sass-lint](https://github.com/sasstools/sass-lint) which conventionally uses a `.sass-lint.yml` file.

So the reason behind this choice was purely a conventional one based upon the linter being used at the time, but really makes no difference. If you want to use `.scss-lint.yml` you may specify it in `ember-cli-build.js`:

    var app = new EmberApp(defaults, {
      scssLintOptions: {
        config: '.scss-lint.yml'
      }
    }

**Comment by michaelfich** [comment]
Awesome!  Thanks so much for the quick response @tomasbasham.
