### ISSUE TITLE
Colorized Output

### ISSUE THREAD

**Issue by mscarchilli** [tomasbasham/ember-cli-scss-lint#6]
It would be really nice to have a colorized output like the grunt-scss-lint package has.

https://github.com/ahmednuaman/grunt-scss-lint#colorizeoutput

**Comment by tomasbasham** [comment]
Similar to #7 you should try passing the `color` option. If this does not work you should probably try making an issue on [broccoli-scss-lint](https://github.com/artursmirnov/broccoli-scss-lint) since it is this module that interfaces with the scss_lint gem. Besides with the default settings I do get some colourised output in the console

<img width="1440" alt="screen shot 2016-06-13 at 21 16 37" src="https://cloud.githubusercontent.com/assets/3389856/16021719/31b4c598-31ac-11e6-8a3c-fdf45861250c.png">

Were you perhaps hinting for more colour?

**Comment by mscarchilli** [comment]
For example, when I'm in grunt using lint I get something like the following image. Color range aside since that's more specific to my PS1 bash prompt. Overall, it's not major, would just be nice to have. Coming from Grunt and having to work in broccoli is frustrating enough, but to have a little love from home makes it so much nicer. I'd convert the Ember project over to Grunt if it would't be major hassle.

grunt-scss-lint uses the following if I remember correctly. 

https://github.com/ahmednuaman/grunt-scss-lint#colorizeoutput
https://github.com/sickill/rainbow#windows-support
https://github.com/cosmo0920/win32-api
https://github.com/djberg96/windows-api
https://github.com/djberg96/windows-pr

![ss](https://cloud.githubusercontent.com/assets/1730810/16023458/c1f8980e-3171-11e6-8d85-a5a86c21863f.jpg)
